openapi: "3.0.1"
info:
  title: "Lottogesellschaft API"
  description: "API für die Verwaltung von Lottoscheinen und Ziehungen"
  version: "1.0.0"
paths:
  /lottoschein/zufallsschein:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LottoSchein"
  /lottoschein/erstellen:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LottoSchein"
  /lottoschein/abgeben:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LottoSchein"
        required: true
      responses:
        "400":
          description: "400 response"
          content: {}
        "201":
          description: "201 response"
          content: {}
components:
  schemas:

    Kreuz:
      type: "integer"
      minimum: 1
      maximum: 49
      description: "Einzelnes Kreuz in einem Lottoscheinfeld."
      format: "int32"

    Superzahl:
      maximum: 9
      minimum: 1
      type: "integer"
      description: "Superzahl zwischen 1 und 9"
      format: "int32"

    Lottoscheinnummer:
      maximum: 9999999
      minimum: 1000000
      type: "integer"
      description: "Eindeutige Lottoscheinnummer"
      format: "int32"

    LottoSchein:
      required:
      - "lottoscheinnummer"
      - "superzahl"
      type: "object"
      properties:
        superzahl:
          $ref: "#/components/schemas/Superzahl"
        lottoscheinnummer:
          $ref: "#/components/schemas/Lottoscheinnummer"
        felder:
          type: array
          maxItems: 6
          items:
            $ref: "#/components/schemas/LottoFeld"

    LottoFeld:
      type: "object"
      properties:
        kreuze:
          type: array
          maxItems: 6
          items:
            $ref: "#/components/schemas/Kreuz"
         